- block:
  - name: Record pre_check result
    ansible.builtin.set_fact:
      patch_report: >-
        {{
          patch_report | default({}) | combine({
            'pre_check_status': {
              'status': 'passed' if ansible_distribution in supported_distros else 'failed',
              'os': ansible_distribution,
              'os_version': ansible_distribution_version
            }
          }, recursive=True)
        }}

  - name: Add failure reason if unsupported OS
    ansible.builtin.set_fact:
      patch_report: "{{ patch_report | combine({'pre_check_status': {'reason': 'Unsupported OS: ' + ansible_distribution}}, recursive=True) }}"
    when: ansible_distribution not in supported_distros

  - name: Fail host if not a supported OS
    ansible.builtin.fail:
      msg: "HOSTNAME: {{ inventory_hostname }} | Not a supported OS: {{ ansible_distribution }}"
    when: ansible_distribution not in supported_distros
