- name: "Auto Patching Playbook"
  gather_facts: true
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - vars/main.yml
  vars:
    report_dir: "{{ local_dir }}/patch"
    report_file: "{{ report_dir }}/{{ inventory_hostname }}_status.json"

  roles:
    - pre_check
    - stop_services
    - patch
    - reboot
    - check_services
