- name: "Auto Patching Playbook"
  gather_facts: true
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - vars/main.yml
  vars:
    lambda_report_url: "{{ lambda_sanity_reboot_status_url }}"

  roles:
    - pre_check
    - role: send_report
      vars:
        report_stage: pre_check
    - stop_services
    - role: send_report
      vars:
        report_stage: stop_services
    - reboot
    - role: send_report
      vars:
        report_stage: reboot
    - check_services
    - role: send_report
      vars:
        report_stage: service_health_check
