- block:
  - name: "Rebooting the server"
    become: true
    reboot:
      msg: "HOSTNAME: {{ inventory_hostname }} | Rebooting initiated by Ansible"
      reboot_timeout: 600
      post_reboot_delay: 30

  rescue:
    - name: "Log if reboot failed"
      lineinfile:
        line: "HOSTNAME: {{ inventory_hostname }} | Server reboot failed, PLEASE CHECK THE SERVER"
        dest: "{{ local_dir }}/update.{{ inventory_hostname }}.FAILED"
        create: true
      delegate_to: localhost

    - name: "Fail host if reboot failed"
      fail:
        msg: "HOSTNAME: {{ inventory_hostname }} | Server reboot failed. Skipping patching on this host."